project_id = "vcnodroausotjqabjqcf"

[functions.fetch-rules-repo]
verify_jwt = false

[functions.ai-component-builder]
verify_jwt = false

[functions.index-rules-source]
verify_jwt = false

[functions.parse-pdf-llamaparse]
verify_jwt = false
