project_id = "vcnodroausotjqabjqcf"

[functions.fetch-rules-repo]
verify_jwt = false

[functions.ai-component-builder]
verify_jwt = false

[functions.extract-units-pdf]
verify_jwt = false

[functions.parse-rules-pdf]
verify_jwt = false

[functions.extract-rules]
verify_jwt = false
